-- Stable seed ids make these defaults safe to reference from admin tools.
-- INSERT OR IGNORE keeps the migration idempotent without overwriting later
-- edits made by administrators.

INSERT OR IGNORE INTO taxonomies (id, code, name, description, translations, selection_mode) VALUES
  ('taxonomy-genre', 'genre', 'Genre', 'Literary form or style of a passage', '{"vi":{"name":"Thể loại","description":"Hình thức hoặc phong cách văn học của bài đọc"}}', 'multiple'),
  ('taxonomy-topic', 'topic', 'Topic', 'Subject matter covered by a passage', '{"vi":{"name":"Chủ đề","description":"Nội dung chính được đề cập trong bài đọc"}}', 'multiple'),
  ('taxonomy-reading-skill', 'reading_skill', 'Reading skill', 'Reading comprehension skill practiced by a passage', '{"vi":{"name":"Kỹ năng đọc","description":"Kỹ năng đọc hiểu được luyện tập trong bài đọc"}}', 'multiple'),
  ('taxonomy-cefr', 'cefr', 'CEFR', 'Approximate language level required to understand a passage', '{"vi":{"name":"CEFR","description":"Mức năng lực ngôn ngữ ước tính cần thiết để hiểu bài đọc"}}', 'single');

INSERT OR IGNORE INTO taxonomy_terms
  (id, taxonomy_id, parent_id, code, name, description, translations, position)
VALUES
  ('genre-fiction', 'taxonomy-genre', NULL, 'fiction', 'Fiction', 'An imagined narrative whose primary purpose is storytelling rather than explaining factual information.', '{"vi":{"name":"Hư cấu","description":"Câu chuyện tưởng tượng có mục đích chính là kể chuyện thay vì giải thích thông tin thực tế"}}', 0),
  ('genre-non-fiction', 'taxonomy-genre', NULL, 'non_fiction', 'Non-fiction', 'A factual text about real people, events, places, processes, or ideas.', '{"vi":{"name":"Phi hư cấu","description":"Văn bản thực tế về người, sự kiện, địa điểm, quá trình hoặc ý tưởng có thật"}}', 1),
  ('genre-poetry', 'taxonomy-genre', NULL, 'poetry', 'Poetry', 'A text organized as verse and shaped by rhythm, sound, imagery, or figurative language.', '{"vi":{"name":"Thơ","description":"Văn bản được tổ chức theo câu thơ và sử dụng nhịp điệu, âm thanh, hình ảnh hoặc ngôn ngữ tu từ"}}', 2),
  ('genre-song', 'taxonomy-genre', NULL, 'song', 'Song', 'Lyrics intended to be sung, often using rhyme, repeated lines, verses, or a chorus.', '{"vi":{"name":"Bài hát","description":"Lời được viết để hát, thường có vần, câu lặp, khổ hoặc điệp khúc"}}', 3),
  ('genre-folktale', 'taxonomy-genre', 'genre-fiction', 'folktale', 'Folktale', 'A traditional story associated with a community or culture and commonly passed between generations.', '{"vi":{"name":"Truyện dân gian","description":"Câu chuyện truyền thống gắn với một cộng đồng hoặc nền văn hóa và thường được truyền qua nhiều thế hệ"}}', 4),
  ('genre-fantasy', 'taxonomy-genre', 'genre-fiction', 'fantasy', 'Fantasy', 'A fictional story containing magic, impossible events, creatures, or imagined worlds.', '{"vi":{"name":"Kỳ ảo","description":"Câu chuyện hư cấu có phép thuật, sự kiện không thể xảy ra, sinh vật hoặc thế giới tưởng tượng"}}', 5),
  ('genre-adventure', 'taxonomy-genre', 'genre-fiction', 'adventure', 'Adventure', 'A fictional story driven by a journey, danger, exploration, or a sequence of difficult challenges.', '{"vi":{"name":"Phiêu lưu","description":"Câu chuyện hư cấu xoay quanh hành trình, nguy hiểm, khám phá hoặc chuỗi thử thách khó khăn"}}', 6),
  ('genre-biography', 'taxonomy-genre', 'genre-non-fiction', 'biography', 'Biography', 'A factual account focused on the life, experiences, and achievements of a real person.', '{"vi":{"name":"Tiểu sử","description":"Bài viết thực tế tập trung vào cuộc đời, trải nghiệm và thành tựu của một người có thật"}}', 7),
  ('genre-informational', 'taxonomy-genre', 'genre-non-fiction', 'informational', 'Informational', 'An expository text whose main purpose is to explain facts, concepts, systems, or processes.', '{"vi":{"name":"Văn bản thông tin","description":"Văn bản có mục đích chính là giải thích sự kiện, khái niệm, hệ thống hoặc quá trình"}}', 8);

INSERT OR IGNORE INTO taxonomy_terms
  (id, taxonomy_id, parent_id, code, name, description, translations, position)
VALUES
  ('topic-animals', 'taxonomy-topic', NULL, 'animals', 'Animals', 'Animals, their behavior, habitats, life cycles, or relationships with people are the central subject.', '{"vi":{"name":"Động vật","description":"Động vật, hành vi, môi trường sống, vòng đời hoặc mối quan hệ của chúng với con người là nội dung trung tâm"}}', 0),
  ('topic-family', 'taxonomy-topic', NULL, 'family', 'Family', 'Family members, relationships, home life, or shared family experiences are central to the passage.', '{"vi":{"name":"Gia đình","description":"Thành viên, mối quan hệ, đời sống gia đình hoặc trải nghiệm chung của gia đình là nội dung trung tâm"}}', 1),
  ('topic-school', 'taxonomy-topic', NULL, 'school', 'School', 'School life, classrooms, learning, teachers, classmates, or school activities are central to the passage.', '{"vi":{"name":"Trường học","description":"Đời sống trường học, lớp học, việc học, giáo viên, bạn học hoặc hoạt động ở trường là nội dung trung tâm"}}', 2),
  ('topic-community', 'taxonomy-topic', NULL, 'community', 'Community', 'Neighborhoods, occupations, public services, shared spaces, or civic participation are central topics.', '{"vi":{"name":"Cộng đồng","description":"Khu dân cư, nghề nghiệp, dịch vụ công, không gian chung hoặc sự tham gia cộng đồng là chủ đề chính"}}', 3),
  ('topic-nature', 'taxonomy-topic', NULL, 'nature', 'Nature', 'The natural world, such as plants, weather, seasons, landforms, or natural events, is the main focus.', '{"vi":{"name":"Thiên nhiên","description":"Thế giới tự nhiên như thực vật, thời tiết, mùa, địa hình hoặc hiện tượng tự nhiên là trọng tâm"}}', 4),
  ('topic-science', 'taxonomy-topic', NULL, 'science', 'Science', 'Scientific concepts, observations, experiments, evidence, or explanations of how the world works are central.', '{"vi":{"name":"Khoa học","description":"Khái niệm khoa học, quan sát, thí nghiệm, bằng chứng hoặc cách giải thích thế giới là nội dung trung tâm"}}', 5),
  ('topic-technology', 'taxonomy-topic', NULL, 'technology', 'Technology', 'Tools, machines, computers, engineering, inventions, or their uses and effects are central to the passage.', '{"vi":{"name":"Công nghệ","description":"Công cụ, máy móc, máy tính, kỹ thuật, phát minh hoặc cách sử dụng và tác động của chúng là nội dung trung tâm"}}', 6),
  ('topic-health', 'taxonomy-topic', NULL, 'health', 'Health', 'The body, nutrition, hygiene, exercise, safety, emotions, or physical and mental well-being are central topics.', '{"vi":{"name":"Sức khỏe","description":"Cơ thể, dinh dưỡng, vệ sinh, vận động, an toàn, cảm xúc hoặc sức khỏe thể chất và tinh thần là chủ đề chính"}}', 7),
  ('topic-culture', 'taxonomy-topic', NULL, 'culture', 'Culture', 'Customs, traditions, celebrations, arts, beliefs, or ways of life shared by a group are central.', '{"vi":{"name":"Văn hóa","description":"Phong tục, truyền thống, lễ hội, nghệ thuật, niềm tin hoặc lối sống chung của một nhóm là nội dung trung tâm"}}', 8),
  ('topic-environment', 'taxonomy-topic', NULL, 'environment', 'Environment', 'Ecosystems, conservation, pollution, climate, resources, or human impact on nature are central topics.', '{"vi":{"name":"Môi trường","description":"Hệ sinh thái, bảo tồn, ô nhiễm, khí hậu, tài nguyên hoặc tác động của con người lên thiên nhiên là chủ đề chính"}}', 9);

INSERT OR IGNORE INTO taxonomy_terms
  (id, taxonomy_id, parent_id, code, name, description, translations, position)
VALUES
  ('skill-vocabulary', 'taxonomy-reading-skill', NULL, 'vocabulary', 'Vocabulary', 'Determine the meaning, nuance, or appropriate use of words and phrases, including meaning from context.', '{"vi":{"name":"Từ vựng","description":"Xác định nghĩa, sắc thái hoặc cách dùng phù hợp của từ và cụm từ, bao gồm suy ra nghĩa từ ngữ cảnh"}}', 0),
  ('skill-main-idea', 'taxonomy-reading-skill', NULL, 'main_idea', 'Main idea', 'Identify the central message or most important point that the whole passage communicates.', '{"vi":{"name":"Ý chính","description":"Xác định thông điệp trung tâm hoặc điểm quan trọng nhất mà toàn bộ bài đọc truyền đạt"}}', 1),
  ('skill-key-details', 'taxonomy-reading-skill', NULL, 'key_details', 'Key details', 'Find and recall explicit facts or supporting details that explain or support the main idea.', '{"vi":{"name":"Chi tiết quan trọng","description":"Tìm và ghi nhớ sự kiện hoặc chi tiết được nêu trực tiếp để giải thích hoặc hỗ trợ ý chính"}}', 2),
  ('skill-sequencing', 'taxonomy-reading-skill', NULL, 'sequencing', 'Sequencing', 'Recognize or reconstruct the chronological, procedural, or logical order of events and steps.', '{"vi":{"name":"Trình tự","description":"Nhận biết hoặc sắp xếp lại thứ tự thời gian, quy trình hoặc logic của sự kiện và các bước"}}', 3),
  ('skill-cause-effect', 'taxonomy-reading-skill', NULL, 'cause_effect', 'Cause and effect', 'Identify why something happens and the direct or indirect results that follow.', '{"vi":{"name":"Nguyên nhân và kết quả","description":"Xác định lý do một sự việc xảy ra và các kết quả trực tiếp hoặc gián tiếp theo sau"}}', 4),
  ('skill-compare-contrast', 'taxonomy-reading-skill', NULL, 'compare_contrast', 'Compare and contrast', 'Identify meaningful similarities and differences between people, objects, events, settings, or ideas.', '{"vi":{"name":"So sánh và đối chiếu","description":"Xác định điểm giống và khác có ý nghĩa giữa người, vật, sự kiện, bối cảnh hoặc ý tưởng"}}', 5),
  ('skill-inference', 'taxonomy-reading-skill', NULL, 'inference', 'Inference', 'Combine textual evidence with prior knowledge to understand information that is implied but not directly stated.', '{"vi":{"name":"Suy luận","description":"Kết hợp bằng chứng trong bài với kiến thức đã biết để hiểu thông tin được ngụ ý nhưng không nêu trực tiếp"}}', 6),
  ('skill-prediction', 'taxonomy-reading-skill', NULL, 'prediction', 'Prediction', 'Use evidence from the text to anticipate a likely next event, outcome, or conclusion.', '{"vi":{"name":"Dự đoán","description":"Dùng bằng chứng trong bài để dự đoán sự kiện, kết quả hoặc kết luận có khả năng xảy ra tiếp theo"}}', 7);

INSERT OR IGNORE INTO taxonomy_terms
  (id, taxonomy_id, parent_id, code, name, description, translations, position)
VALUES
  ('cefr-a1', 'taxonomy-cefr', NULL, 'a1', 'A1', 'Very short, concrete texts using familiar everyday words, simple sentence patterns, repetition, and strong contextual support.', '{"vi":{"name":"A1","description":"Văn bản rất ngắn và cụ thể, dùng từ quen thuộc hằng ngày, mẫu câu đơn giản, lặp lại và có nhiều hỗ trợ từ ngữ cảnh"}}', 0),
  ('cefr-a2', 'taxonomy-cefr', NULL, 'a2', 'A2', 'Short, straightforward texts about familiar needs and routines, using common vocabulary, simple connectors, and directly stated information.', '{"vi":{"name":"A2","description":"Văn bản ngắn, rõ ràng về nhu cầu và sinh hoạt quen thuộc, dùng từ phổ biến, liên từ đơn giản và thông tin được nêu trực tiếp"}}', 1),
  ('cefr-b1', 'taxonomy-cefr', NULL, 'b1', 'B1', 'Clear texts on familiar topics with connected paragraphs, common idioms, varied everyday tenses, and straightforward descriptions or opinions.', '{"vi":{"name":"B1","description":"Văn bản rõ ràng về chủ đề quen thuộc, có các đoạn liên kết, thành ngữ phổ biến, nhiều thì thông dụng và mô tả hoặc ý kiến trực tiếp"}}', 2),
  ('cefr-b2', 'taxonomy-cefr', NULL, 'b2', 'B2', 'Detailed texts on concrete or abstract topics with a wider vocabulary, complex clauses, sustained arguments, and some implied relationships.', '{"vi":{"name":"B2","description":"Văn bản chi tiết về chủ đề cụ thể hoặc trừu tượng, dùng vốn từ rộng, mệnh đề phức tạp, lập luận kéo dài và một số quan hệ ngụ ý"}}', 3),
  ('cefr-c1', 'taxonomy-cefr', NULL, 'c1', 'C1', 'Long, structurally complex texts with nuanced or implicit meaning, less frequent vocabulary, idiomatic language, and dense argumentation.', '{"vi":{"name":"C1","description":"Văn bản dài, cấu trúc phức tạp, ý nghĩa tinh tế hoặc hàm ẩn, từ ít gặp, ngôn ngữ thành ngữ và lập luận dày đặc"}}', 4),
  ('cefr-c2', 'taxonomy-cefr', NULL, 'c2', 'C2', 'Highly complex literary, academic, or specialized texts requiring precise interpretation of style, abstraction, idiom, and culturally dependent meaning.', '{"vi":{"name":"C2","description":"Văn bản văn học, học thuật hoặc chuyên ngành rất phức tạp, đòi hỏi hiểu chính xác phong cách, tính trừu tượng, thành ngữ và ý nghĩa phụ thuộc văn hóa"}}', 5);
