/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/env.d.ts` (hash: 395d7114fb64f9ad2101d749850aa8b9)
interface __BaseEnv_Env {
	ASSETS: R2Bucket;
	DB: D1Database;
	ASSET_BASE_URL: string;
	AI_ASSESSMENT_URL: string;
	JWT_PUBLIC_KEY_PEM: string;
	AI_INTERNAL_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ASSET_BASE_URL" | "AI_ASSESSMENT_URL" | "JWT_PUBLIC_KEY_PEM" | "AI_INTERNAL_SECRET_KEY">> {}
}
